version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/A101.Application"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/A101.Domain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/A101.Infrastructure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/A101.RevitPlugin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/tests/A101.Application.Tests"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/tests/A101.Domain.Tests"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/tests/A101.Infrastructure.Tests"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/ml"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
